obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.3
inflater_layer:
  inflation_radius: 0.3
  cost_scaling_factor: 1.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser_link, data_type: LaserScan, topic: laserscan, marking: false, clearing: true}

