DWAPlannerROS: 
  max_vel_x: 0.4
  min_vel_x: 0.1
  acc_lim_x: 20.0
  acc_lim_theta: 20.0
  acc_lim_trans: 3.0
  max_vel_y: 0.0 
  min_vel_y: -0.0 
  min_vel_trans: 0.0
  path_distance_bias: 2.0
  holonomic_robot: false